language: python
ssudo: required

services:
  - docker


# Setup anaconda
before_install:
  - docker build -f Dockerfile.python2 -t py2 .
  - docker ps -a

# Install packages
#install:
#  - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-learn
#  - pip install -r requirements.txt --quiet
#  - pip install -r requirements_dev.txt --quiet
#  - git clone git@github.com:GPflow/GPflow.git
#  - cd GPflow
#  - python setup.py install

# Run tests
script:
  - docker run py2 flake8 safe_learning --exclude "test*.py,__init__.py" --ignore=E402,W503 --show-source
  - docker run py2 flake8 safe_learning --filename="__init__.py,test*.py" --ignore=F,E402,W503 --show-source
  - docker run py2 nosetests --with-doctest --nocapture --with-coverage --cover-min-percentage=80 --cover-erase --cover-package=safe_learning safe_learning
  - docker run py2 pydocstyle safe_learning --match='(?!__init__).*\.py'

