language: python
ssudo: required

services:
  - docker

env:
  - PYTHON=python2
  - PYTHON=python3

# Setup anaconda
install:
  - docker pull befelix/lyapunov-learning-private:${PYTHON} || true
  - docker build -f Dockerfile.${PYTHON} -t test-image .
  - docker ps -a

# Run tests
script:
  - docker run test-image flake8 safe_learning --exclude "test*.py,__init__.py" --ignore=E402,W503 --show-source
  - docker run test-image flake8 safe_learning --filename="__init__.py,test*.py" --ignore=F,E402,W503 --show-source
  - docker run test-image nosetests --with-doctest --nocapture --with-coverage --cover-min-percentage=80 --cover-erase --cover-package=safe_learning safe_learning
  - docker run test-image pydocstyle safe_learning --match='(?!__init__).*\.py'

